{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_test.py:16: AssertionError"}, "description": "this test fails", "start": 1691486146456, "stop": 1691486146456, "uuid": "2ac07580-0d80-482c-a7e5-0d44fc268ed6", "historyId": "8dfa276f51c29a8a2eb4352fff16bb5a", "testCaseId": "8dfa276f51c29a8a2eb4352fff16bb5a", "fullName": "test_test#test_failure", "labels": [{"name": "suite", "value": "test_test"}, {"name": "host", "value": "DELL-0O8SAEAM4H"}, {"name": "thread", "value": "3248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_test"}]}