{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_test.py:16: AssertionError"}, "description": "this test fails", "start": 1691486126157, "stop": 1691486126157, "uuid": "5b217792-365a-4c56-b603-e32a00401b9f", "historyId": "8dfa276f51c29a8a2eb4352fff16bb5a", "testCaseId": "8dfa276f51c29a8a2eb4352fff16bb5a", "fullName": "test_test#test_failure", "labels": [{"name": "suite", "value": "test_test"}, {"name": "host", "value": "DELL-0O8SAEAM4H"}, {"name": "thread", "value": "19088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_test"}]}